
const icon_category = {
    'Delivery': 'fa-solid fa-truck',
    'Reservations': "fa-solid fa-calendar-day",
    'Burgers': "fa-solid fa-burger",
    'Japanese': "fa-solid fa-fish-fins",
    'Chinese': "fa-solid fa-bowl-rice",
    'Mexican': "fa-solid fa-pepper-hot",
    'Italian': "fa-solid fa-pizza-slice",
    'Thai': "fa-solid fa-fish",
    'Contractors': "fa-solid fa-hammer",
    'Landscaping': "fa-solid fa-tree",
    'Electricians': "fa-solid fa-plug",
    'Locksmiths': "fa-solid fa-lock",
    'Home Cleaners': "fa-solid fa-broom",
    'Movers': "fa-solid fa-people-carry-box",
    'HVAC': "fa-solid fa-house",
    'Plumbers': "fa-solid fa-sink",
    'Auto Repair': "fa-solid fa-screwdriver-wrench",
    'Car Dealers': "fa-solid fa-car",
    'Auto Detailing': "fa-solid fa-pump-soap",
    'Oil Change': "fa-solid fa-oil-can",
    'Body Shops': "fa-solid fa-car-side",
    'Parking': "fa-solid fa-square-parking",
    'Car Wash': "fa-solid fa-soap",
    'Towing': "fa-solid fa-truck-front",
    'Dry Cleaning': "fa-solid fa-hand-sparkles",
    'Hair Salons': "fa-solid fa-scissors",
    'Phone Repair': "fa-solid fa-mobile-screen",
    'Gyms': "fa-solid fa-dumbbell",
    'Bars': "fa-solid fa-martini-glass",
    'Massage': "fa-solid fa-spa",
    'Nightlife': "fa-solid fa-champagne-glasses",
    'Shopping': "fa-solid fa-basket-shopping"
}

export default icon_category